### PR TITLE
Updated w/ more profile data and README instructions

### PR DESCRIPTION
**Pull request by joelvh**
Updated the gem to return more profile data. Also added instructions to README to make it easier to get things setup.

### CODE REVIEW

**Comment by joelvh** [comment]
hi @rmanalan any interest in pulling this in?

**Comment by rmanalan** [comment]
Merging... thx @joelvh !!!

**Comment by joelvh** [comment]
great! Thanks @rmanalan

**Comment by joelvh** [comment]
@rmanalan are you planning on publishing the new version of the gem?

**Comment by rmanalan** [comment]
(lol) yes... once I figure out how to do it again. It's been a long time since I've done any ruby/gem work.

**Comment by joelvh** [comment]
ah! got it. happy to take over maintenance of the gem :-)

**Comment by rmanalan** [comment]
Go for it then! Thanks!!!!

**Comment by joelvh** [comment]
@rmanalan I'll email you at your email address in the gemspec to transfer things, if that's ok?

**Comment by rmanalan** [comment]
yep... or rich at hipchat

**Pull request merged**
